# Define common configurations using an anchor
x-base-config: &base_config
  networks:
    - app_net

services:
  zamans-container:
    <<: *base_config
    image: nginx:alpine
    container_name: zamans-container
    ports:
      - "8080:80"
    env_file:
      - .env
    command: >
      sh -c "echo ${MYSELF} loves ${FAVORITE_FRUIT} and works as a ${JOB}. "
    labels:
      description: "A container demonstrating YAML syntax"
      creator: zaman

  second-container:
    <<: *base_config
    image: alpine:latest
    container_name: second-container
    command: >
      sh -c "echo This is the second container" # Sleep to keep the container running

networks:
  app_net:
    driver: bridge
